### ISSUE TITLE
Order input

### ISSUE THREAD

**Issue by shahab271069** [TY-Cheng/torchvinecopulib#24]
Hi there,

Thank you for your pure python implementation. I have a problem that I can not give the order of variables for fitting and need to give complete matrix of R-vine structure. Is it possible to give only the order like pyvinecopula?

Shahab

**Comment by TY-Cheng** [comment]
Hi @shahab271069 ,

Currently it's possible to give partial order during c/d/r-vine fitting, such that later with fitted models we can do conditional simulation/quantile regression, as a regression tool from multivariate X (those column indices in tpl_first when using tvc.vinecop.vcp_from_obs) to multivariate Y. 

In the `./examples` folder there's a `2_cdrvine_condsim_quantreg.ipynb` you may find helpful. The explicit requirements on conditioned/conditioning sets for conditional simulation are designed by intention, nudging users to be clear about which data vertices are they specifying.
